//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace truespectsistema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TruespectEntities : DbContext
    {
        public TruespectEntities()
            : base("name=TruespectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<anios> anios { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<meses> meses { get; set; }
        public virtual DbSet<registro_almacen> registro_almacen { get; set; }
        public virtual DbSet<ciudades> ciudades { get; set; }
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
    }
}
