//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace truespectsistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id_empleado { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string usuario { get; set; }
        public string contraseña { get; set; }
        public string tpo_usuario { get; set; }
        public int id_tpo_usuario { get; set; }
        public string rfc { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public string status { get; set; }
    }
}
